### ISSUE TITLE
Upgrading from v20230508 to v20230530 inflates canister sizes beyond 2MB

### ISSUE THREAD

**Issue by saikatdas0790** [ninegua/ic-nix#61] opened 2023-06-04 11:00 UTC
Hi @ninegua 

Upgrading to the latest ic-nix release increases build outputs from earlier sizes to much larger now. You can test for this here:
https://github.com/go-bazzinga/hot-or-not-backend-canister/

The current repo uses the v20230508 version. Try the install script from `scripts/canisters/local_deploy/install_all_canisters.sh`. It installs fine.

Now change the version in the `default.nix` file and try the install script again after clean starting dfx. You'll see the following output:
![image](https://github.com/ninegua/ic-nix/assets/7412443/48ac7c9b-21ef-4bb5-960b-a63a9321d5ea)

Thoughts?

**Comment by ninegua** [comment] 2023-06-05 02:06
It is hard to say what exactly was the cause. But `user_index` is your own canister, right? Was it also around 2.6M in size before? Then it could be that the replica now enforces a lower max allowed size. 

What you can try is to gzip it and use the compressed file directly in the installation. This usually avoids the limit

**Comment by saikatdas0790** [comment] 2023-06-05 10:05
> It is hard to say what exactly was the cause. But `user_index` is your own canister, right? Was it also around 2.6M in size before? Then it could be that the replica now enforces a lower max allowed size.
> 
> What you can try is to gzip it and use the compressed file directly in the installation. This usually avoids the limit

That's the thing. `user_index` was under the limit. 

And I am gzipping. Check [here](https://github.com/go-bazzinga/hot-or-not-backend-canister/blob/ecab36ab2638234b581bf8a7a441377538ddd677/scripts/canisters/local_deploy/install_all_canisters.sh#L41-L50)

**Comment by ninegua** [comment] 2023-06-05 10:49
I suspect your script didn't work the way you intended.

`dfx canister install` would try to compile the Rust binary again, despite that you already gzipped it (which would remove the binary). So dfx is still trying to install the non-gzipped version. To confirm this, look under `target/wasm32-unknown-unknown/release/` after running your shell script. I suspect both the gz file and the original wasm exist.

To solve the problem, try adding `--wasm <file>` to `dfx canister install` to specifically point to the gzip file. (same solution was offered in the forum thread, and you seem to have confirmed it worked afterwards. Not sure why your script is missing this)

**Comment by ninegua** [comment] 2023-06-05 11:13
Ignore what said above, looks like the gzip file itself is 2319792 bytes. But I also had no problem installing it to my local replica using 20230530 release.

**Comment by ninegua** [comment] 2023-06-05 11:44
I also noticed that with 20230508 it is producing binary that is much smaller, likely because ic-wasm (the optimizer) is being used as a separate command. I'm trying out a fix now, will update later.

**Comment by saikatdas0790** [comment] 2023-06-05 12:12
> Note that I got a smaller size for `user_index.wasm.gz` than yours. I'm using rustup with `nightly` channel.

As an aside, I'm using Rust stable channel

**Comment by ninegua** [comment] 2023-06-05 16:04
Problem is fixed in the latest master branch. A new release is building

**Comment by ninegua** [comment] 2023-06-08 16:46
Can you try this patch?

```
diff --git a/dfx.json b/dfx.json
index 6dbb3ff..d23c2d7 100644
--- a/dfx.json
+++ b/dfx.json
@@ -44,7 +44,8 @@
       "declarations": {
         "node_compatibility": true,
         "output": "./export/declarations/user_index"
-      }
+      },
+      "gzip": true
     },
     "internet_identity": {
       "type": "custom",
```

Basically adding `"gzip": true` to your canister configuration in `dfx.json`.

**Closed** 2023-06-21 12:20 UTC
